### ISSUE TITLE
doesnt work on lights out mode

### ISSUE THREAD

**Issue by bridgebucket** [RoootTheFox/ctp-twitter#1]
theme only works on dim, contrary to what is said in readme.md

**Comment by RoootTheFox** [comment]
That's new to me, will look into this when I get home (~2 hours)

**Comment by RoootTheFox** [comment]
My bad, I think I confused "dim" and "lights out" when I wrote the README, thanks for telling me about this!

Fixed in [`739c63a`](https://github.com/RoootTheFox/ctp-twitter/commit/739c63a33f698e003863bc89d8f49a6407da981d).
